language: objective-c
podfile: Podfile
osx_image: xcode7

before_install:
- gem install cocoapods
- export LANG=en_US.UTF-8
- brew update
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
- pod install

script:
- xctool clean build -workspace PassportScanner.xcworkspace -scheme PassportScanner -sdk iphonesimulator9.0 ONLY_ACTIVE_ARCH=NO
